export const codeFolderStructure=[
    {
        title:'Research',
        show:true,
        subFolders:[
            {
                title:'Folder1',
                show:false,
                subFolders:[
                    {
                        title:'SubFolder11',
                        show:false
                    },
                    {
                        title:'SubFolder12',
                        show:false
                    },
                    {
                        title:'SubFolder13',
                        show:false
                    }
                ]
            },
            {
                title:'Folder2',
                show:false,
                subFolders:[
                    {
                        title:'SubFolder21',
                        show:false
                    },
                    {
                        title:'SubFolder22',
                        show:false
                    },
                    {
                        title:'SubFolder23',
                        show:false
                    }
                ]
            },
        ]
    }
];